//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaNam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        [Required(ErrorMessage = "Vui long nhap noi dung comments.")]
        [StringLength(50, ErrorMessage = "Binh luan khong qua 50 ky tu.")]
        public string CommentText { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public int ProID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
