//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaNam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
        [Required(ErrorMessage = "Vui long nhap so dien thoai.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "So dien thoai phai dung 10 so.")]
        public string CusPhone { get; set; }
        [Required(ErrorMessage = "Vui long nhap mat khau.")]
        [MinLength(6, ErrorMessage = "Mat khau phai co it nhat 6 ky tu.")]
        public string CusPassword { get; set; }
        [Required(ErrorMessage = "Vui long nhap ten Customer.")]
        [StringLength(20, ErrorMessage = "Ten Customer khong duoc vuot qua 20 ki tu.")]
        public string CusName { get; set; }
        public string CusEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
