//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaNam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> ProSupID { get; set; }
        public Nullable<int> OrderID { get; set; }
        [Required(ErrorMessage = "So luong la truong bat buoc.")]
        [Range(1, int.MaxValue, ErrorMessage = "So luong phai la so duong.")]
        public Nullable<int> Quantity { get; set; }
        [Required(ErrorMessage = "Gia Nha Nam là truong bat buoc.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Gia Nha Nam phai la so duong.")]
        public Nullable<double> UnitPrice { get; set; }
        [Required(ErrorMessage = "Gia bia la truong bat buoc.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Gia bia phai la so duong.")]
        public Nullable<double> OldPrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProDetail ProDetail { get; set; }
    }
}
