//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaNam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProDeID { get; set; }
        public int ProID { get; set; }
        public int SupID { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,0}")]
        [Required(ErrorMessage = "Gia Nha Nam là truong bat buoc.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Gia Nha Nam phai la so duong.")]
        public Nullable<double> UnitPrice { get; set; }

        [DisplayFormat(DataFormatString = "{0:#,0}")]
        [Required(ErrorMessage = "Gia bia la truong bat buoc.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Gia bia phai la so duong.")]
        public Nullable<double> OldPrice { get; set; }

        public string Size { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }

        [Required(ErrorMessage = "So luong ton kho la truong bat buoc.")]
        [Range(1, int.MaxValue, ErrorMessage = "So luong ton kho phai la so duong.")]
        public int RemainQuantity { get; set; }

        //[Required(ErrorMessage = "So luong ban ra la truong bat buoc.")]
        //[Range(1, int.MaxValue, ErrorMessage = "So luong ban ra phai la so duong.")]
        public Nullable<int> SoldQuantity { get; set; }

        //[Required(ErrorMessage = "So luot xem la truong bat buoc.")]
        //[Range(1, int.MaxValue, ErrorMessage = "So luot xem phai la so duong.")]
        public Nullable<int> ViewQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
