//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaNam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.ProDetails = new HashSet<ProDetail>();
        }
    
        public int SupID { get; set; }
        [Required(ErrorMessage = "Vui long nhap ten nha cung cap.")]
        [StringLength(20, ErrorMessage = "Ten nha cung cap khong duoc vuot qua 20 ki tu.")]
        public string SupName { get; set; }
        [Required(ErrorMessage = "Vui long nhap dia chi nha cung cap.")]
        [StringLength(50, ErrorMessage = "Dia chi nha cung cap khong duoc vuot qua 50 ki tu.")]
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProDetail> ProDetails { get; set; }
    }
}
